version: '3.10'

services:
  web:
    build: ./DRF
    env_file:
      - .env
    volumes:
      - ./DRF:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - '6379:6379'
  celery:
    build: ./DRF
    entrypoint: celery -A DRF worker -l info
    volumes:
      - ./DRF/:/usr/scr/app
    env_file:
      - ./DRF/.env
    depends_on:
      - redis
      - db
  celery-beat:
    build: ./DRF
    entrypoint: celery -A DRF beat -l info
    volumes:
      - ./DRF/:/usr/src/app/
    env_file:
      - ./DRF/.env
    depends_on:
      - db
      - redis
      - celery

